name: Linux 

# You can setup workflows to run automatically on specific branches.
# Read the HTML workflow to understand that.
on:
  workflow_dispatch:

jobs:
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
    # Installing Haxe.
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.2

    # Obtaining Haxe Libraries for compilation.
    # This uses a custom version of HXCPP with some optimizations.
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/Assorion/HXCPP_O3
          haxelib install lime 
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons 

    # Random Github BS as always, just keep this here.   
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION

    # Compilation of the source code. x64
      - name: Compilation 64-Bit
        run: haxelib run lime build Project.xml linux -release --app-version="4.0.0-${{ github.run_id}}"

    # Provides the 64-Bit file for download.
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: Linux-x64-Build
          path: 'export/release/linux/bin'
      
    # Compilation of the source code. x86
      - name: Compilation 32-Bit
        run: |
          sudo apt-get install gcc-multilib g++-multilib
          haxelib run lime build Project.xml linux -32 -release --app-version="4.0.0-${{ github.run_id}}"

    # Provides the 32-Bit file for download.
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: Linux-x86-Build
          path: 'export/release/linux/bin'
