name: Windows

# You can setup workflows to run automatically on specific branches.
# Read the HTML workflow to understand that.
on:
  workflow_dispatch:

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
    # Install Haxe. 
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      
    # Obtaining Haxe Libraries for compilation.
    # This uses a custom version of HXCPP with some optimizations.
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp
          haxelib install lime 7.9.0
          haxelib install openfl 9.2.2
          haxelib install flixel 4.9.0 
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.7.0
        shell: cmd

    # Random Github BS as always, just keep this here.
      - name: Version Tag
        run: echo "${{github.run_id}}" > VERSION
        
    # Compilation of the source code.
      - name: Compile 64-Bit Version
        run: haxelib run lime build windows -release --app-version="4.0.0-${{ github.run_id}}"

    # Provides the 64-Bit file for download.
      - name: Publish x64 Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows-x64
          path: export/release/windows/bin
      
    # Compilation of the game using 32-bit.
      - name: Compile 32-Bit Version
        run: |
          haxelib set hxcpp 4.3.2
          haxelib run lime build windows -32 -release --app-version="4.0.0-${{ github.run_id}}"

    # Provides the 32-Bit file for download.
      - name: Publish x86 Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows-x86
          path: export/release/windows/bin

